# Generated by Django 4.2.11 on 2024-04-15 09:29

import cloudinary.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('chucvu', models.CharField(choices=[('HOCSINH', 'hocsinh'), ('GIANGVIEN', 'giangvien'), ('GIAOVU', 'giaovu'), ('ADMIN', 'admin')], max_length=50)),
                ('avt', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HoiDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hoi Dong',
                'verbose_name_plural': 'Hoi Dong',
            },
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Khoa',
            },
        ),
        migrations.CreateModel(
            name='KhoaLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=200)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaycapnhat', models.DateTimeField(auto_now=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('trangthai', models.BooleanField(default=1)),
                ('giaovu', models.ForeignKey(limit_choices_to={'chucvu': 'giaovu'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gv_huongdan', models.ManyToManyField(limit_choices_to={'chucvu': 'giangvien'}, related_name='gv_huongdans', to=settings.AUTH_USER_MODEL)),
                ('hoidong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kltn.hoidong')),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kltn.khoa')),
                ('sinhvien', models.ManyToManyField(limit_choices_to={'chucvu': 'hocsinh'}, related_name='sinhviens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khoa Luan',
                'verbose_name_plural': 'Khoa Luan',
            },
        ),
        migrations.CreateModel(
            name='TieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(choices=[('HINH THUC', 'hinh thuc'), ('PHAN BIEN', 'phan bien'), ('THUC HIEN', 'thuc hien'), ('DO KHO', 'do kho'), ('MO RONG', 'mo rong'), ('UNG DUNG', 'ung dung')], max_length=100)),
            ],
            options={
                'verbose_name': 'Tieu Chi',
                'verbose_name_plural': 'Tieu Chi',
            },
        ),
        migrations.CreateModel(
            name='ThanhVien_HoiDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaitro', models.CharField(choices=[('CHU TICH', 'chu tich'), ('THU KY', 'thu ky'), ('PHAN BIEN', 'phan bien'), ('THANH VIEN KHAC', 'thanh vien khac')], default='THANH VIEN KHAC', max_length=100)),
                ('hoidong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kltn.hoidong')),
                ('thanhvien', models.ForeignKey(limit_choices_to={'chucvu': 'giangvien'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thanh Vien - Hoi Dong',
                'verbose_name_plural': 'Thanh Vien - Hoi Dong',
                'unique_together': {('thanhvien', 'hoidong')},
            },
        ),
        migrations.CreateModel(
            name='KhoaLuan_TieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_diem', models.FloatField()),
                ('nhanxet', models.CharField(max_length=100)),
                ('khoaluan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kltn.khoaluan')),
                ('nguoi_danhgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tieuchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kltn.tieuchi')),
            ],
        ),
        migrations.AddField(
            model_name='khoaluan',
            name='tieuchis',
            field=models.ManyToManyField(related_name='tieuchis', through='kltn.KhoaLuan_TieuChi', to='kltn.tieuchi'),
        ),
        migrations.AddField(
            model_name='hoidong',
            name='thanhviens',
            field=models.ManyToManyField(related_name='thanhviens', through='kltn.ThanhVien_HoiDong', to=settings.AUTH_USER_MODEL),
        ),
    ]
